### ISSUE TITLE
quic fingerprint starts with a "u", not "q"

### ISSUE THREAD

**Issue by awelzel** [anthonykasza/ja4#1]
With Zeek 6.1, the QUIC analyzer is bulit-in. Using this package, the ja4 hash for a connection, however, starts with a "u".

This snippet never reaches the "quic" check:

https://github.com/anthonykasza/ja4/blob/382b79d26a68da4e38c595f16fc505a83a264b3c/scripts/main.zeek#L47-L52

```
docker run -v$(pwd)/testing/btest/Traces:/Traces --rm -it zeek/zeek:6.1
# zkg install --force https://github.com/anthonykasza/ja4
# zeek -C -r /Traces/quic/curl-8.1.2-dev-http3-www-google-de.pcap ja4
# zeek-cut -m uid ja4 < ja4.log 
uid	ja4
CnTXoD3dKVFILRkRFe	u13d0308h3_55b375c5d22e_f0736a66fa6b
# zeek-cut -m  uid service < conn.log 
uid	service
CnTXoD3dKVFILRkRFe	ssl,quic
```

**Comment by anthonykasza** [comment]
Thank you @awelzel. Let me know if efdab142df489d01f0153d8f0b0ef17a4109e91a does not address your concerns.
