### ISSUE TITLE
Suggestion for improvements

### ISSUE THREAD

**Issue by ghost** [anthonykasza/ja4#2]
Hi Anthony,

thank you for making this JA4 plugin for zeek! I have installed the plugin in here and had a few suggestions which I'd like to share with you. If you think these suggestions are sound I can also help you by making a PR somewhere along the line :-) Obviously some suggestions can be done by scripting on our side too.

Instead of having a separate ja4 log file I think it is more logical to have the ja4 hash to be added to the SSL::Info block as that is where the scope of the ja4 hash is relevant. By adding the ja4 to the ssl.log, the ja4 hash is where other information of the ssl handshake is as well.

I tried to solve this creating a zeek script that also listens to the same event you use: 'connection_state_remove' to add the ja4 hash to SSL::Info, but it appears the SSL log has already been written to disk when connection_state_remove is called. So this was not a logical place to hook.

I'd say it would be more logical to handle the setting of ja4 hash to the ssl_client_hello or ssl_connection_established events (I think you suggest something of the sort in a comment in the code).

Also, I think it would be beneficial to split the 'set_ja4' function into two functions: one that calculates the hash, and the another that attaches it to the connection. In that case people can use ja4 = JA4::calculate_hash(c$ssl) in scripts if they just want the value then and there.

Let me know what you think :-)

**Comment by anthonykasza** [comment]
Hello. Thank you for using this code and for your feedback.

It's my understanding that the Zeek team isn't keen to major changes in the default "base" logging formats. Other packages, for example [zeek-tls-log-alternative](https://github.com/0xxon/zeek-tls-log-alternative) which provides alternatives to the default ssl logging format, do so by creating a new log stream. This practice is not strictly followed, however. For an example of how one may extend the SSL::Info record, and thus the ssl log format, see [ssl-log-ext](https://github.com/zeek/zeek/blob/master/scripts/policy/protocols/ssl/ssl-log-ext.zeek). To extend the ssl log file, you will need to set its JA4 value prior to `SSL::finish()` being called. To achieve this you could try setting the JA4 value from `SSL::finalize_ssl()`, `SSL::log_ssl()`, or `Log::log_stream_policy()`.

I think 2 functions is an unnecessary change but I am willing to listen. Prior to splitting `set_ja4()` into 2 functions could you please explain a bit more? Under what circumstances would a script developer want to call `calculate()` but not `set()`? Additionally, how should function behave if a script developer calls `calculate()` while Zeek is in the middle of parsing a ClientHello message?

If you provide any of these changes in a PR I'll happily merge.

**Comment by anthonykasza** [comment]
I have moved the logging logic from the `connection_state_remove` event to the `SSL::finalize_ssl` hook. That may be helpful to your goal of extending the default ssl log format. Let me know if you have any other feedback.
